data:
  train_data_file: data/ec/CLEAN_split100_esm1b_t33_ec_above_5_single_label_train.pt
  valid_data_file: data/ec/CLEAN_split100_esm1b_t33_ec_above_5_single_label_val.pt
  test_data_file: data/ec/new_esm1b_t33_single_label_ec_above_5.pt
  label_file: data/ec/CLEAN_split100_ec_above_5_single_label_list.json
  label_name: ec
  dataset_type: SingleLabelSequenceDataset

model:
  model_type: MLPModel
  input_dim: 1280
  num_layers: 5
  hidden_dims: [5120, 5120, 2560, 2560]
  out_dim: null
  dropout: 0.5

train:
  seed: 0
  batch_size: 1000
  num_epochs: 10000
  lr: 1.e-4
  weight_decay: 0.0
  patience: 40
  loss: NCLoss
  sup_criterion: CrossEntropyLoss
  lambda1: 1.0
  lambda2: 1.0
  lambda_CE: 0.0
  optimizer: Adam
  start_NC_epoch: 0
  nc1: NC1Loss_v2_cosine
  nc2: NC2Loss