data:
  train_data_file: data/ec/multilabel/sprot_10_1022_esm1b_t33_train.pt
  valid_data_file: data/ec/multilabel/sprot_10_1022_esm1b_t33_val.pt
  test_data_file: data/ec/multilabel/sprot_10_1022_esm1b_t33_test_filtered.pt
  original_train_data_file: data/ec/multilabel/sprot_10_1022_esm1b_t33_train_val.pt
  label_file: data/ec/multilabel/label_list_train_val.json
  label_name: ec
  dataset_type: MultiLabelDataset

model:
  model_type: MLPModel
  input_dim: 1280
  num_layers: 4
  hidden_dims: [5120, 5120, 5000]
  out_dim: null
  dropout: 0.5

train:
  seed: 0
  batch_size: 1000
  num_epochs: 10000
  lr: 1.e-4
  weight_decay: 0.0
  patience: 20
  loss: NCLoss
  sup_criterion: CrossEntropyLoss
  lambda1: 1.0
  lambda2: 1.0
  lambda_CE: 0.0
  optimizer: Adam
  start_NC_epoch: 0
  nc1: NC1Loss_v2_cosine
  nc2: NC2Loss