data:
  train_data_file: data/ec/sprot_10_1022_esm2_t33_ec_above_10_single_label_train.pt
  valid_data_file: data/ec/sprot_10_1022_esm2_t33_ec_above_10_single_label_val.pt
  test_data_file: data/ec/sprot_10_1022_esm2_t33_ec_above_10_single_label_test.pt
  label_file: data/ec/all_level_ec_list_above_10.json
  label_name: ec
  dataset_type: SingleLabelHierarchyDataset

model:
  model_type: SprofECModel
  input_dim: 1280
  num_layers: 3
  hidden_dims: [5120, 2560]
  out_dim: null
  dropout: 0.5
  CM_path: data/ec/CM_EC_all_level_label_above_10.pt

train:
  seed: 0
  batch_size: 256
  num_epochs: 1000
  lr: 1.e-3
  weight_decay: 1.e-4
  patience: 20
  loss: CrossEntropyLoss
  optimizer: Adam