pretrained_model_dir: logs_debug/train_mlp_single_label_NC_deeper_esm1b_2024_03_30__11_24_38_NC_v2_cosine_bs1000
data:
  train_data_file: data/ec/sprot_10_1022_esm1b_t33_ec_above_10_single_label_train.pt
  valid_data_file: data/ec/sprot_10_1022_esm1b_t33_ec_above_10_single_label_val.pt
  test_data_file: data/ec/sprot_10_1022_esm1b_t33_ec_above_10_single_label_test.pt
  label_file: data/ec/swissprot_ec_list_above_10.json
  label_name: ec
  dataset_type: SingleLabelSequenceDataset

model:
  model_type: MLPModel
  input_dim: 1280
  num_layers: 5
  hidden_dims: [5120, 5120, 2560, 2000]
  out_dim: null
  dropout: 0.5

train:
  seed: 0
  batch_size: 1000
  num_epochs: 10000
  lr: 5.e-5
  weight_decay: 0.0
  patience: 20
  loss: CrossEntropyLoss
  optimizer: Adam
  freeze_encoder: True
  load_pretrained_means: True