data:
  train_data_file: data/pfam/sprot_10_1022_esm2_t33_pfam_above_10_single_label_train.pt
  valid_data_file: data/pfam/sprot_10_1022_esm2_t33_pfam_above_10_single_label_val.pt
  test_data_file: data/pfam/sprot_10_1022_esm2_t33_pfam_above_10_single_label_test.pt
  label_file: data/pfam/pfam_single_label_list.json
  label_name: pfam
  dataset_type: SingleLabelSequenceDataset

model:
  model_type: MLPModel
  input_dim: 1280
  num_layers: 3
  hidden_dims: [2560, 2000]
  out_dim: null
  dropout: 0.5

train:
  seed: 0
  batch_size: 512
  num_epochs: 1000
  lr: 1.e-3
  weight_decay: 1.e-4
  patience: 20
  loss: CrossEntropyLoss
  optimizer: Adam