data:
  train_data_file: data/ec/sprot_10_1022_esm2_t33_ec_above_10_single_label_train.pt
  valid_data_file: data/ec/sprot_10_1022_esm2_t33_ec_above_10_single_label_val.pt
  test_data_file: data/ec/sprot_10_1022_esm2_t33_ec_above_10_single_label_test.pt
  label_file: data/ec/swissprot_ec_list_above_10.json
  label_name: ec
  dataset_type: SingleLabelSequenceDataset

model:
  model_type: MLPModel
  input_dim: 1280
  num_layers: 3
  hidden_dims: [2560, 2000]
  out_dim: null
  dropout: 0.5

train:
  seed: 0
  batch_size: 256
  num_epochs: 10000
  lr: 1.e-4
  weight_decay: 1.e-5
  patience: 40
  loss: NCLoss
  sup_criterion: CrossEntropyLoss
  lambda1: 1.0
  lambda2: 1.0
  lambda_CE: 1.0
  optimizer: Adam
  start_NC_epoch: 30
  nc1: NC1Loss_cosine
  nc2: NC2Loss