data:
  train_data_file: data/ec/sprot_10_1022_esm2_t33_ec_above_10_single_label_train.pt
  valid_data_file: data/ec/sprot_10_1022_esm2_t33_ec_above_10_single_label_val.pt
  test_data_file: data/ec/sprot_10_1022_esm2_t33_ec_above_10_single_label_test.pt
  label_file: data/ec/swissprot_ec_list_level3.json
  label_name: ec
  label_level: 3
  dataset_type: SingleLabelSequenceDataset

model:
  model_type: MLPModel
  input_dim: 1280
  num_layers: 3
  hidden_dims: [640, 320]
  out_dim: null
  dropout: 0.5

train:
  seed: 0
  batch_size: 512
  num_epochs: 1000
  lr: 1.e-3
  weight_decay: 1.e-4
  patience: 20
  loss: CrossEntropyLoss
  optimizer: Adam